### ISSUE TITLE
Parse error while deploying smart contracts

### ISSUE THREAD

**Issue by nidasafiasyed** [kaleido-io/kaleido-hackathon#1]
Hello,
         We are getting a parse error while deploying our smart contract using the curl command.
![screenshot 68](https://user-images.githubusercontent.com/37712412/45837824-3d2e3480-bcde-11e8-9ddb-3c4452d9935e.png)

We have created another .js file, for the backend to send JSON RPC calls. Is it because of this? Can you please help us out?

**Comment by dbryan0516** [comment]
Hmm that sounds like a jq error, meaning your JSON response may be invalid.

But glad you figured it out!

**Comment by nidasafiasyed** [comment]
Well, that was a false alarm, and we're still trying to figure it out.

**Comment by dbryan0516** [comment]
Ahh okay, Have you tried it without JQ? It will be less readable, but you can see if it's valid JSON and it may help debug the issue?

**Comment by dbryan0516** [comment]
Did removing the ` | jq ` help?

**Comment by AbhishaB** [comment]
Hi...I am Abhisha, Nida's teammate for the hackathon. So when I removed JQ I got the below error.

![image](https://user-images.githubusercontent.com/36175238/45845829-33afc700-bcf4-11e8-9989-1a990dfd5bb1.png)

I am also getting the same message when I try to open localhost:3000 on my browser. 

Thanks!

**Comment by dbryan0516** [comment]
Ahh okay, so that would be a problem with your nodejs code. 

Did you start the app before using the curl command? 

If so, you may need to check the spelling and case of that endpoint. So in your app.js make sure you have a '/governmentcontract/deploy' post endpoint declared and defined

**Comment by AbhishaB** [comment]
Thank you so much!! Yes, it was a spelling error!
